services:
  - type: web
    name: stock-forecaster-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: stock-forecaster-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
